# Generated by Django 4.2.1 on 2023-06-25 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymodel',
            name='Manufacturer',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
