# Generated by Django 4.2.1 on 2023-07-16 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_mymodel_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='Link',
            field=models.URLField(max_length=500, null=True),
        ),
    ]
